# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static HTML and CSS app to Azure Web App - prueba14

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Crea un archivo ZIP con todos los archivos del repositorio
      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      # 3. Despliega la aplicación estática en Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'prueba14' # Nombre de tu Web App en Azure
          slot-name: 'Production' # Cambia si usas un slot diferente
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE10B47CF3714E27B6528D0B1C010F94 }}
          package: release.zip
